server:
  port: 8513  # 服务端口
spring:
  application:
    name: service-cart  # Nacos服务名称（服务注册与发现的标识）
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos服务注册中心地址
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource  # 使用HikariCP连接池（SpringBoot默认推荐）
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL8.x驱动类（注意cj包路径）
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root  # 数据库用户名
    password: 123456  # 数据库密码
  data:
    redis:
      host: localhost
      port: 6379

# MyBatis-Plus 核心配置
mybatis-plus:
  # Mapper映射文件位置（xml文件）
  mapper-locations: classpath:mapper/**/*.xml
  # 实体类别名扫描包（简化XML中的类名引用）
  type-aliases-package: com.spzx.product.model.entity
  # 全局配置
  global-config:
    db-config:
      # 主键类型：AUTO(自增)、NONE(空)、INPUT(手动输入)、ASSIGN_ID(雪花算法)、ASSIGN_UUID(UUID)
      id-type: ASSIGN_ID
       #表名前缀（如果表名有统一前缀，可在此配置，实体类无需加前缀）
#      table-prefix: tb_
#      #逻辑删除字段名（全局配置逻辑删除的字段）开启后原来的物理删除就不会执行，而是执行is_deleted=1
#      logic-delete-field: isDeleted
#      # 逻辑删除-未删除值
#      logic-not-delete-value: 0
#      # 逻辑删除-已删除值
#      logic-delete-value: 1
#配置MyBatis的原生配置（如驼峰命名转换）
  configuration:
    # 开启驼峰命名自动转换（数据库字段：user_name → 实体类属性：userName）
    map-underscore-to-camel-case: true
    # 开启SQL日志打印（开发环境建议开启，生产环境关闭）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭一级缓存（避免多线程下数据不一致）
    local-cache-scope: STATEMENT
    # 设置默认的执行器（SIMPLE:普通执行器；REUSE:重用预处理语句；BATCH:批量执行器）
    default-executor-type: REUSE
minio:
  endpoint: http://169.254.19.248:9000  # 你的MinIO服务地址
  access-key: minioadmin                # MinIO账号
  secret-key: minioadmin                # MinIO密码
  bucket-name: spzx                     # 目标桶名